In [10]:
from tensorflow.keras.preprocessing.text import one_hot

In [11]:
### sentences
sent=[ 'the glass of milk',
'the glass of juice',
'the cup of tea',
'I am a good boy',
'I am a good developer',
'understand the meaning of words',
'your videos are good',]

In [12]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [13]:
## Define the vocabulary size
voc_size=10000

In [14]:
### One hot represenation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[1156, 4998, 17, 6148],
 [1156, 4998, 17, 6516],
 [1156, 1669, 17, 7024],
 [9346, 5025, 7459, 7202, 4642],
 [9346, 5025, 7459, 7202, 2336],
 [4060, 1156, 5550, 17, 5111],
 [327, 2792, 4172, 7202]]

In [16]:
## word embedding represenattion
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential


In [ ]:
import numpy as np

In [17]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding="pre",maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 1156 4998   17 6148]
 [   0    0    0    0 1156 4998   17 6516]
 [   0    0    0    0 1156 1669   17 7024]
 [   0    0    0 9346 5025 7459 7202 4642]
 [   0    0    0 9346 5025 7459 7202 2336]
 [   0    0    0 4060 1156 5550   17 5111]
 [   0    0    0    0  327 2792 4172 7202]]


In [18]:
## feature representaton
dim=10

In [20]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [22]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [23]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 254ms/step


array([[[-1.4889017e-03,  3.2283019e-02,  1.9887719e-02,  2.4669278e-02,
          2.8292682e-02, -1.8483162e-02,  4.4796798e-02, -1.9679343e-02,
         -3.1742826e-02, -2.2286916e-02],
        [-1.4889017e-03,  3.2283019e-02,  1.9887719e-02,  2.4669278e-02,
          2.8292682e-02, -1.8483162e-02,  4.4796798e-02, -1.9679343e-02,
         -3.1742826e-02, -2.2286916e-02],
        [-1.4889017e-03,  3.2283019e-02,  1.9887719e-02,  2.4669278e-02,
          2.8292682e-02, -1.8483162e-02,  4.4796798e-02, -1.9679343e-02,
         -3.1742826e-02, -2.2286916e-02],
        [-1.4889017e-03,  3.2283019e-02,  1.9887719e-02,  2.4669278e-02,
          2.8292682e-02, -1.8483162e-02,  4.4796798e-02, -1.9679343e-02,
         -3.1742826e-02, -2.2286916e-02],
        [-3.2464493e-02, -4.9508538e-02,  4.4567976e-02,  1.3611052e-02,
          2.0431969e-02, -3.6057197e-02, -1.6987719e-02,  1.0815561e-02,
         -4.2460859e-05,  1.4212694e-02],
        [ 1.1226941e-02, -4.7671605e-02, -4.5131076e-02,  2.

In [24]:
embedded_docs[0]

array([   0,    0,    0,    0, 1156, 4998,   17, 6148])

In [25]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 111ms/step


array([[-1.4889017e-03,  3.2283019e-02,  1.9887719e-02,  2.4669278e-02,
         2.8292682e-02, -1.8483162e-02,  4.4796798e-02, -1.9679343e-02,
        -3.1742826e-02, -2.2286916e-02],
       [-1.4889017e-03,  3.2283019e-02,  1.9887719e-02,  2.4669278e-02,
         2.8292682e-02, -1.8483162e-02,  4.4796798e-02, -1.9679343e-02,
        -3.1742826e-02, -2.2286916e-02],
       [-1.4889017e-03,  3.2283019e-02,  1.9887719e-02,  2.4669278e-02,
         2.8292682e-02, -1.8483162e-02,  4.4796798e-02, -1.9679343e-02,
        -3.1742826e-02, -2.2286916e-02],
       [-1.4889017e-03,  3.2283019e-02,  1.9887719e-02,  2.4669278e-02,
         2.8292682e-02, -1.8483162e-02,  4.4796798e-02, -1.9679343e-02,
        -3.1742826e-02, -2.2286916e-02],
       [-3.2464493e-02, -4.9508538e-02,  4.4567976e-02,  1.3611052e-02,
         2.0431969e-02, -3.6057197e-02, -1.6987719e-02,  1.0815561e-02,
        -4.2460859e-05,  1.4212694e-02],
       [ 1.1226941e-02, -4.7671605e-02, -4.5131076e-02,  2.7165897e-03,
   